
class Autogenerated {
  List<Newslist> newslist;
  Notice notice;
  int newsCount;
  int catalog;
  int pageSize;

  Autogenerated({this.newslist, this.notice, this.newsCount, this.catalog,
      this.pageSize});


  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['newslist'] != null) {
      newslist = new List<Newslist>();
      json['newslist'].forEach((v) {
        newslist.add(new Newslist.fromJson(v));
      });
    }
    notice =
    json['notice'] != null ? new Notice.fromJson(json['notice']) : null;

    newsCount=json[newsCount];
    catalog=json[catalog];
    pageSize=json[pageSize];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.newslist != null) {
      data['newslist'] = this.newslist.map((v) => v.toJson()).toList();
    }
    if (this.notice != null) {
      data['notice'] = this.notice.toJson();
    }
    return data;
  }
}

class Newslist {
  int id;
  String author;
  String pubDate;
  String title;
  int authorid;
  int commentCount;
  int type;

  Newslist(
      {this.id,
        this.author,
        this.pubDate,
        this.title,
        this.authorid,
        this.commentCount,
        this.type});

  Newslist.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    author = json['author'];
    pubDate = json['pubDate'];
    title = json['title'];
    authorid = json['authorid'];
    commentCount = json['commentCount'];
    type = json['type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['author'] = this.author;
    data['pubDate'] = this.pubDate;
    data['title'] = this.title;
    data['authorid'] = this.authorid;
    data['commentCount'] = this.commentCount;
    data['type'] = this.type;
    return data;
  }
}

class Notice {
  int replyCount;
  int msgCount;
  int fansCount;
  int referCount;

  Notice({this.replyCount, this.msgCount, this.fansCount, this.referCount});

  Notice.fromJson(Map<String, dynamic> json) {
    replyCount = json['replyCount'];
    msgCount = json['msgCount'];
    fansCount = json['fansCount'];
    referCount = json['referCount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['replyCount'] = this.replyCount;
    data['msgCount'] = this.msgCount;
    data['fansCount'] = this.fansCount;
    data['referCount'] = this.referCount;
    return data;
  }
}
